shapes:

  - name: test01

    num: 4

    time: 5

    vertices:
      - [0.0, 0.0]
      - [0.0, 0.2]
      - [0.2, 0.2]
      - [0.2, 0.0]

    start_pose:
      position: [0.3, 0.3, 0.3]
      rpy:  [0.0, 1.57, 1.57]
    
